export enum RouteNames {
  HOME = "HOME",
  TWELFTH_BUTTON = "TWELFTH_BUTTON",
  BUTTON_8 = "BUTTON_8",
  BUTTON_1 = "BUTTON_1",
  TENTH_BUTTON = "TENTH_BUTTON",
  FOURTH_BUTTON = "FOURTH_BUTTON",
  BUTTON_SIXTH = "BUTTON_SIXTH"
}
