export enum RouteNames {
  HOME = "HOME",
  TWELFTH_BUTTON = "TWELFTH_BUTTON",
  BUTTON_9 = "BUTTON_9",
  TENTH_BUTTON = "TENTH_BUTTON",
  FOURTH_BUTTON = "FOURTH_BUTTON",
  BUTTON_SIXTH = "BUTTON_SIXTH"
}
